// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: accounts.sql

package sqlcgen

import (
	"context"
)

const accountByIdentity = `-- name: AccountByIdentity :one
SELECT a.id, a.tier
FROM account_identities i
JOIN accounts a ON a.id = i.account_id
WHERE i.provider = ? AND i.subject = ?
`

type AccountByIdentityParams struct {
	Provider string
	Subject  string
}

type AccountByIdentityRow struct {
	ID   string
	Tier string
}

func (q *Queries) AccountByIdentity(ctx context.Context, arg AccountByIdentityParams) (AccountByIdentityRow, error) {
	row := q.db.QueryRowContext(ctx, accountByIdentity, arg.Provider, arg.Subject)
	var i AccountByIdentityRow
	err := row.Scan(&i.ID, &i.Tier)
	return i, err
}

const accountByTokenHash = `-- name: AccountByTokenHash :one
SELECT a.id, a.tier
FROM account_tokens t
JOIN accounts a ON a.id = t.account_id
WHERE t.token_hash = ?
`

type AccountByTokenHashRow struct {
	ID   string
	Tier string
}

func (q *Queries) AccountByTokenHash(ctx context.Context, tokenHash []byte) (AccountByTokenHashRow, error) {
	row := q.db.QueryRowContext(ctx, accountByTokenHash, tokenHash)
	var i AccountByTokenHashRow
	err := row.Scan(&i.ID, &i.Tier)
	return i, err
}

const createAccount = `-- name: CreateAccount :exec
INSERT INTO accounts (id, tier, created_at) VALUES (?, ?, ?)
`

type CreateAccountParams struct {
	ID        string
	Tier      string
	CreatedAt string
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) error {
	_, err := q.db.ExecContext(ctx, createAccount, arg.ID, arg.Tier, arg.CreatedAt)
	return err
}

const createAccountIdentity = `-- name: CreateAccountIdentity :exec
INSERT INTO account_identities (provider, subject, account_id, created_at) VALUES (?, ?, ?, ?)
`

type CreateAccountIdentityParams struct {
	Provider  string
	Subject   string
	AccountID string
	CreatedAt string
}

func (q *Queries) CreateAccountIdentity(ctx context.Context, arg CreateAccountIdentityParams) error {
	_, err := q.db.ExecContext(ctx, createAccountIdentity,
		arg.Provider,
		arg.Subject,
		arg.AccountID,
		arg.CreatedAt,
	)
	return err
}

const createAccountToken = `-- name: CreateAccountToken :exec
INSERT INTO account_tokens (token_hash, account_id, created_at) VALUES (?, ?, ?)
`

type CreateAccountTokenParams struct {
	TokenHash []byte
	AccountID string
	CreatedAt string
}

func (q *Queries) CreateAccountToken(ctx context.Context, arg CreateAccountTokenParams) error {
	_, err := q.db.ExecContext(ctx, createAccountToken, arg.TokenHash, arg.AccountID, arg.CreatedAt)
	return err
}

const deleteAccountToken = `-- name: DeleteAccountToken :exec
DELETE FROM account_tokens WHERE token_hash = ?
`

func (q *Queries) DeleteAccountToken(ctx context.Context, tokenHash []byte) error {
	_, err := q.db.ExecContext(ctx, deleteAccountToken, tokenHash)
	return err
}

const ensureQuotaRow = `-- name: EnsureQuotaRow :exec
INSERT INTO quota_usage (account_id, period, used) VALUES (?, ?, 0)
ON CONFLICT (account_id, period) DO NOTHING
`

type EnsureQuotaRowParams struct {
	AccountID string
	Period    string
}

func (q *Queries) EnsureQuotaRow(ctx context.Context, arg EnsureQuotaRowParams) error {
	_, err := q.db.ExecContext(ctx, ensureQuotaRow, arg.AccountID, arg.Period)
	return err
}

const quotaUsed = `-- name: QuotaUsed :one
SELECT used FROM quota_usage WHERE account_id = ? AND period = ?
`

type QuotaUsedParams struct {
	AccountID string
	Period    string
}

func (q *Queries) QuotaUsed(ctx context.Context, arg QuotaUsedParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, quotaUsed, arg.AccountID, arg.Period)
	var used int64
	err := row.Scan(&used)
	return used, err
}

const refundQuota = `-- name: RefundQuota :exec
UPDATE quota_usage SET used = used - 1
WHERE account_id = ? AND period = ? AND used > 0
`

type RefundQuotaParams struct {
	AccountID string
	Period    string
}

func (q *Queries) RefundQuota(ctx context.Context, arg RefundQuotaParams) error {
	_, err := q.db.ExecContext(ctx, refundQuota, arg.AccountID, arg.Period)
	return err
}

const useQuota = `-- name: UseQuota :one
UPDATE quota_usage SET used = used + 1
WHERE account_id = ?1 AND period = ?2 AND used < ?3
RETURNING used
`

type UseQuotaParams struct {
	AccountID  string
	Period     string
	QuotaLimit int64
}

func (q *Queries) UseQuota(ctx context.Context, arg UseQuotaParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, useQuota, arg.AccountID, arg.Period, arg.QuotaLimit)
	var used int64
	err := row.Scan(&used)
	return used, err
}
