// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: candidates.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const abandonPendingCandidates = `-- name: AbandonPendingCandidates :execrows
UPDATE rule_candidates
SET status = 'rejected', reason = ?, updated_at = ?
WHERE status = 'pending'
`

type AbandonPendingCandidatesParams struct {
	Reason    sql.NullString
	UpdatedAt string
}

func (q *Queries) AbandonPendingCandidates(ctx context.Context, arg AbandonPendingCandidatesParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, abandonPendingCandidates, arg.Reason, arg.UpdatedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getCandidate = `-- name: GetCandidate :one
SELECT id, domain, account_id, status, reason, rule_version, created_at, updated_at
FROM rule_candidates
WHERE id = ? AND account_id = ?
`

type GetCandidateParams struct {
	ID        string
	AccountID string
}

func (q *Queries) GetCandidate(ctx context.Context, arg GetCandidateParams) (RuleCandidate, error) {
	row := q.db.QueryRowContext(ctx, getCandidate, arg.ID, arg.AccountID)
	var i RuleCandidate
	err := row.Scan(
		&i.ID,
		&i.Domain,
		&i.AccountID,
		&i.Status,
		&i.Reason,
		&i.RuleVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const hasPendingCandidate = `-- name: HasPendingCandidate :one
SELECT EXISTS (
  SELECT 1 FROM rule_candidates WHERE domain = ? AND status = 'pending'
)
`

func (q *Queries) HasPendingCandidate(ctx context.Context, domain string) (bool, error) {
	row := q.db.QueryRowContext(ctx, hasPendingCandidate, domain)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const insertCandidate = `-- name: InsertCandidate :exec
INSERT INTO rule_candidates (id, domain, account_id, status, reason, rule_version, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertCandidateParams struct {
	ID          string
	Domain      string
	AccountID   string
	Status      string
	Reason      sql.NullString
	RuleVersion sql.NullInt64
	CreatedAt   string
	UpdatedAt   string
}

func (q *Queries) InsertCandidate(ctx context.Context, arg InsertCandidateParams) error {
	_, err := q.db.ExecContext(ctx, insertCandidate,
		arg.ID,
		arg.Domain,
		arg.AccountID,
		arg.Status,
		arg.Reason,
		arg.RuleVersion,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const lastGenerationFailure = `-- name: LastGenerationFailure :one
SELECT failed_at FROM generation_failures WHERE domain = ?
`

func (q *Queries) LastGenerationFailure(ctx context.Context, domain string) (string, error) {
	row := q.db.QueryRowContext(ctx, lastGenerationFailure, domain)
	var failed_at string
	err := row.Scan(&failed_at)
	return failed_at, err
}

const recordGenerationFailure = `-- name: RecordGenerationFailure :exec
INSERT INTO generation_failures (domain, reason, failed_at)
VALUES (?, ?, ?)
ON CONFLICT (domain) DO UPDATE SET reason = excluded.reason, failed_at = excluded.failed_at
`

type RecordGenerationFailureParams struct {
	Domain   string
	Reason   string
	FailedAt string
}

func (q *Queries) RecordGenerationFailure(ctx context.Context, arg RecordGenerationFailureParams) error {
	_, err := q.db.ExecContext(ctx, recordGenerationFailure, arg.Domain, arg.Reason, arg.FailedAt)
	return err
}

const resolveCandidates = `-- name: ResolveCandidates :exec
UPDATE rule_candidates
SET status = ?, reason = ?, rule_version = ?, updated_at = ?
WHERE domain = ? AND status = 'pending'
`

type ResolveCandidatesParams struct {
	Status      string
	Reason      sql.NullString
	RuleVersion sql.NullInt64
	UpdatedAt   string
	Domain      string
}

func (q *Queries) ResolveCandidates(ctx context.Context, arg ResolveCandidatesParams) error {
	_, err := q.db.ExecContext(ctx, resolveCandidates,
		arg.Status,
		arg.Reason,
		arg.RuleVersion,
		arg.UpdatedAt,
		arg.Domain,
	)
	return err
}
