// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: devices.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const createDevice = `-- name: CreateDevice :exec
INSERT INTO devices (id, token_hash, app_version, webview_version, created_at)
VALUES (?, ?, ?, ?, ?)
`

type CreateDeviceParams struct {
	ID             string
	TokenHash      []byte
	AppVersion     string
	WebviewVersion sql.NullString
	CreatedAt      string
}

func (q *Queries) CreateDevice(ctx context.Context, arg CreateDeviceParams) error {
	_, err := q.db.ExecContext(ctx, createDevice,
		arg.ID,
		arg.TokenHash,
		arg.AppVersion,
		arg.WebviewVersion,
		arg.CreatedAt,
	)
	return err
}

const deleteDevice = `-- name: DeleteDevice :exec
DELETE FROM devices WHERE id = ?
`

func (q *Queries) DeleteDevice(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteDevice, id)
	return err
}

const deviceByTokenHash = `-- name: DeviceByTokenHash :one
SELECT id, app_version, webview_version, created_at
FROM devices
WHERE token_hash = ?
`

type DeviceByTokenHashRow struct {
	ID             string
	AppVersion     string
	WebviewVersion sql.NullString
	CreatedAt      string
}

func (q *Queries) DeviceByTokenHash(ctx context.Context, tokenHash []byte) (DeviceByTokenHashRow, error) {
	row := q.db.QueryRowContext(ctx, deviceByTokenHash, tokenHash)
	var i DeviceByTokenHashRow
	err := row.Scan(
		&i.ID,
		&i.AppVersion,
		&i.WebviewVersion,
		&i.CreatedAt,
	)
	return i, err
}
