// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"database/sql"
)

type Account struct {
	ID        string
	Tier      string
	CreatedAt string
}

type AccountToken struct {
	TokenHash []byte
	AccountID string
	CreatedAt string
}

type Device struct {
	ID             string
	TokenHash      []byte
	AppVersion     string
	WebviewVersion sql.NullString
	CreatedAt      string
}

type QuotaUsage struct {
	AccountID string
	Period    string
	Used      int64
}

type Rule struct {
	Domain      string
	Version     int64
	Body        []byte
	Fingerprint sql.NullString
	Status      string
	CreatedAt   string
}

type RuleCandidate struct {
	ID          string
	Domain      string
	AccountID   string
	Status      string
	Reason      sql.NullString
	RuleVersion sql.NullInt64
	CreatedAt   string
	UpdatedAt   string
}

type RuleHealth struct {
	Domain        string
	Version       int64
	Successes     int64
	EmptyResults  int64
	BackwardJumps int64
}

type RuleReport struct {
	Domain     string
	Version    int64
	DeviceID   string
	Problem    string
	Url        string
	Correction sql.NullString
	CreatedAt  string
}

type SyncClock struct {
	AccountID string
	Seq       int64
}

type SyncField struct {
	AccountID string
	Entity    string
	RecordID  string
	Field     string
	Value     string
	UpdatedAt string
	Seq       int64
}

type SyncTombstone struct {
	AccountID string
	Entity    string
	RecordID  string
	UpdatedAt string
	Seq       int64
}
