// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: rules.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const addRuleHealth = `-- name: AddRuleHealth :one
INSERT INTO rule_health (domain, version, successes, empty_results, backward_jumps)
VALUES (?, ?, ?, ?, ?)
ON CONFLICT (domain, version) DO UPDATE SET
  successes = successes + excluded.successes,
  empty_results = empty_results + excluded.empty_results,
  backward_jumps = backward_jumps + excluded.backward_jumps
RETURNING successes, empty_results, backward_jumps
`

type AddRuleHealthParams struct {
	Domain        string
	Version       int64
	Successes     int64
	EmptyResults  int64
	BackwardJumps int64
}

type AddRuleHealthRow struct {
	Successes     int64
	EmptyResults  int64
	BackwardJumps int64
}

func (q *Queries) AddRuleHealth(ctx context.Context, arg AddRuleHealthParams) (AddRuleHealthRow, error) {
	row := q.db.QueryRowContext(ctx, addRuleHealth,
		arg.Domain,
		arg.Version,
		arg.Successes,
		arg.EmptyResults,
		arg.BackwardJumps,
	)
	var i AddRuleHealthRow
	err := row.Scan(&i.Successes, &i.EmptyResults, &i.BackwardJumps)
	return i, err
}

const addRuleReport = `-- name: AddRuleReport :exec
INSERT INTO rule_reports (domain, version, device_id, problem, url, correction, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
ON CONFLICT DO NOTHING
`

type AddRuleReportParams struct {
	Domain     string
	Version    int64
	DeviceID   string
	Problem    string
	Url        string
	Correction sql.NullString
	CreatedAt  string
}

func (q *Queries) AddRuleReport(ctx context.Context, arg AddRuleReportParams) error {
	_, err := q.db.ExecContext(ctx, addRuleReport,
		arg.Domain,
		arg.Version,
		arg.DeviceID,
		arg.Problem,
		arg.Url,
		arg.Correction,
		arg.CreatedAt,
	)
	return err
}

const fingerprintedRules = `-- name: FingerprintedRules :many
SELECT r.body, r.status, r.created_at
FROM rules r
WHERE r.fingerprint IS NOT NULL
  AND r.status != 'retired'
  AND r.version = (
    SELECT MAX(r2.version) FROM rules r2
    WHERE r2.domain = r.domain AND r2.status != 'retired'
  )
`

type FingerprintedRulesRow struct {
	Body      []byte
	Status    string
	CreatedAt string
}

func (q *Queries) FingerprintedRules(ctx context.Context) ([]FingerprintedRulesRow, error) {
	rows, err := q.db.QueryContext(ctx, fingerprintedRules)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FingerprintedRulesRow{}
	for rows.Next() {
		var i FingerprintedRulesRow
		if err := rows.Scan(&i.Body, &i.Status, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRule = `-- name: GetRule :one
SELECT body, status, created_at FROM rules WHERE domain = ? AND version = ?
`

type GetRuleParams struct {
	Domain  string
	Version int64
}

type GetRuleRow struct {
	Body      []byte
	Status    string
	CreatedAt string
}

func (q *Queries) GetRule(ctx context.Context, arg GetRuleParams) (GetRuleRow, error) {
	row := q.db.QueryRowContext(ctx, getRule, arg.Domain, arg.Version)
	var i GetRuleRow
	err := row.Scan(&i.Body, &i.Status, &i.CreatedAt)
	return i, err
}

const insertRule = `-- name: InsertRule :exec
INSERT INTO rules (domain, version, body, fingerprint, status, created_at)
VALUES (?, ?, ?, ?, ?, ?)
`

type InsertRuleParams struct {
	Domain      string
	Version     int64
	Body        []byte
	Fingerprint sql.NullString
	Status      string
	CreatedAt   string
}

func (q *Queries) InsertRule(ctx context.Context, arg InsertRuleParams) error {
	_, err := q.db.ExecContext(ctx, insertRule,
		arg.Domain,
		arg.Version,
		arg.Body,
		arg.Fingerprint,
		arg.Status,
		arg.CreatedAt,
	)
	return err
}

const latestRule = `-- name: LatestRule :one
SELECT body, status, created_at
FROM rules
WHERE domain = ? AND status != 'retired'
ORDER BY version DESC
LIMIT 1
`

type LatestRuleRow struct {
	Body      []byte
	Status    string
	CreatedAt string
}

func (q *Queries) LatestRule(ctx context.Context, domain string) (LatestRuleRow, error) {
	row := q.db.QueryRowContext(ctx, latestRule, domain)
	var i LatestRuleRow
	err := row.Scan(&i.Body, &i.Status, &i.CreatedAt)
	return i, err
}

const maxRuleVersion = `-- name: MaxRuleVersion :one
SELECT CAST(COALESCE(MAX(version), 0) AS INTEGER) FROM rules WHERE domain = ?
`

func (q *Queries) MaxRuleVersion(ctx context.Context, domain string) (int64, error) {
	row := q.db.QueryRowContext(ctx, maxRuleVersion, domain)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const reportingDevices = `-- name: ReportingDevices :one
SELECT COUNT(DISTINCT device_id) FROM rule_reports WHERE domain = ? AND version = ?
`

type ReportingDevicesParams struct {
	Domain  string
	Version int64
}

func (q *Queries) ReportingDevices(ctx context.Context, arg ReportingDevicesParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, reportingDevices, arg.Domain, arg.Version)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const ruleHealth = `-- name: RuleHealth :one
SELECT successes, empty_results, backward_jumps
FROM rule_health
WHERE domain = ? AND version = ?
`

type RuleHealthParams struct {
	Domain  string
	Version int64
}

type RuleHealthRow struct {
	Successes     int64
	EmptyResults  int64
	BackwardJumps int64
}

func (q *Queries) RuleHealth(ctx context.Context, arg RuleHealthParams) (RuleHealthRow, error) {
	row := q.db.QueryRowContext(ctx, ruleHealth, arg.Domain, arg.Version)
	var i RuleHealthRow
	err := row.Scan(&i.Successes, &i.EmptyResults, &i.BackwardJumps)
	return i, err
}

const setRuleStatus = `-- name: SetRuleStatus :exec
UPDATE rules SET status = ? WHERE domain = ? AND version = ?
`

type SetRuleStatusParams struct {
	Status  string
	Domain  string
	Version int64
}

func (q *Queries) SetRuleStatus(ctx context.Context, arg SetRuleStatusParams) error {
	_, err := q.db.ExecContext(ctx, setRuleStatus, arg.Status, arg.Domain, arg.Version)
	return err
}
