// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sync.sql

package sqlcgen

import (
	"context"
)

const nextSyncSeq = `-- name: NextSyncSeq :one
INSERT INTO sync_clocks (account_id, seq) VALUES (?, 1)
ON CONFLICT (account_id) DO UPDATE SET seq = seq + 1
RETURNING seq
`

func (q *Queries) NextSyncSeq(ctx context.Context, accountID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, nextSyncSeq, accountID)
	var seq int64
	err := row.Scan(&seq)
	return seq, err
}

const putSyncField = `-- name: PutSyncField :exec
INSERT INTO sync_fields (account_id, entity, record_id, field, value, updated_at, seq)
VALUES (?, ?, ?, ?, ?, ?, ?)
ON CONFLICT (account_id, entity, record_id, field) DO UPDATE SET
  value = excluded.value, updated_at = excluded.updated_at, seq = excluded.seq
`

type PutSyncFieldParams struct {
	AccountID string
	Entity    string
	RecordID  string
	Field     string
	Value     string
	UpdatedAt string
	Seq       int64
}

func (q *Queries) PutSyncField(ctx context.Context, arg PutSyncFieldParams) error {
	_, err := q.db.ExecContext(ctx, putSyncField,
		arg.AccountID,
		arg.Entity,
		arg.RecordID,
		arg.Field,
		arg.Value,
		arg.UpdatedAt,
		arg.Seq,
	)
	return err
}

const putSyncTombstone = `-- name: PutSyncTombstone :exec
INSERT INTO sync_tombstones (account_id, entity, record_id, updated_at, seq)
VALUES (?, ?, ?, ?, ?)
ON CONFLICT (account_id, entity, record_id) DO UPDATE SET
  updated_at = excluded.updated_at, seq = excluded.seq
`

type PutSyncTombstoneParams struct {
	AccountID string
	Entity    string
	RecordID  string
	UpdatedAt string
	Seq       int64
}

func (q *Queries) PutSyncTombstone(ctx context.Context, arg PutSyncTombstoneParams) error {
	_, err := q.db.ExecContext(ctx, putSyncTombstone,
		arg.AccountID,
		arg.Entity,
		arg.RecordID,
		arg.UpdatedAt,
		arg.Seq,
	)
	return err
}

const syncAtSeq = `-- name: SyncAtSeq :many
SELECT entity, record_id, field, value, updated_at, seq FROM sync_fields
WHERE sync_fields.account_id = ?1 AND sync_fields.seq = ?2
UNION ALL
SELECT entity, record_id, '' AS field, '' AS value, updated_at, seq FROM sync_tombstones
WHERE sync_tombstones.account_id = ?1 AND sync_tombstones.seq = ?2
`

type SyncAtSeqParams struct {
	AccountID string
	Seq       int64
}

type SyncAtSeqRow struct {
	Entity    string
	RecordID  string
	Field     string
	Value     string
	UpdatedAt string
	Seq       int64
}

func (q *Queries) SyncAtSeq(ctx context.Context, arg SyncAtSeqParams) ([]SyncAtSeqRow, error) {
	rows, err := q.db.QueryContext(ctx, syncAtSeq, arg.AccountID, arg.Seq)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SyncAtSeqRow{}
	for rows.Next() {
		var i SyncAtSeqRow
		if err := rows.Scan(
			&i.Entity,
			&i.RecordID,
			&i.Field,
			&i.Value,
			&i.UpdatedAt,
			&i.Seq,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const syncField = `-- name: SyncField :one
SELECT value, updated_at FROM sync_fields
WHERE account_id = ? AND entity = ? AND record_id = ? AND field = ?
`

type SyncFieldParams struct {
	AccountID string
	Entity    string
	RecordID  string
	Field     string
}

type SyncFieldRow struct {
	Value     string
	UpdatedAt string
}

func (q *Queries) SyncField(ctx context.Context, arg SyncFieldParams) (SyncFieldRow, error) {
	row := q.db.QueryRowContext(ctx, syncField,
		arg.AccountID,
		arg.Entity,
		arg.RecordID,
		arg.Field,
	)
	var i SyncFieldRow
	err := row.Scan(&i.Value, &i.UpdatedAt)
	return i, err
}

const syncSince = `-- name: SyncSince :many
SELECT entity, record_id, field, value, updated_at, seq FROM sync_fields
WHERE sync_fields.account_id = ?2 AND sync_fields.seq > ?3
UNION ALL
SELECT entity, record_id, '' AS field, '' AS value, updated_at, seq FROM sync_tombstones
WHERE sync_tombstones.account_id = ?2 AND sync_tombstones.seq > ?3
ORDER BY seq
LIMIT ?1
`

type SyncSinceParams struct {
	RowLimit  int64
	AccountID string
	Cursor    int64
}

type SyncSinceRow struct {
	Entity    string
	RecordID  string
	Field     string
	Value     string
	UpdatedAt string
	Seq       int64
}

func (q *Queries) SyncSince(ctx context.Context, arg SyncSinceParams) ([]SyncSinceRow, error) {
	rows, err := q.db.QueryContext(ctx, syncSince, arg.RowLimit, arg.AccountID, arg.Cursor)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SyncSinceRow{}
	for rows.Next() {
		var i SyncSinceRow
		if err := rows.Scan(
			&i.Entity,
			&i.RecordID,
			&i.Field,
			&i.Value,
			&i.UpdatedAt,
			&i.Seq,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const syncTombstone = `-- name: SyncTombstone :one
SELECT updated_at FROM sync_tombstones
WHERE account_id = ? AND entity = ? AND record_id = ?
`

type SyncTombstoneParams struct {
	AccountID string
	Entity    string
	RecordID  string
}

func (q *Queries) SyncTombstone(ctx context.Context, arg SyncTombstoneParams) (string, error) {
	row := q.db.QueryRowContext(ctx, syncTombstone, arg.AccountID, arg.Entity, arg.RecordID)
	var updated_at string
	err := row.Scan(&updated_at)
	return updated_at, err
}
