"""Writes android/CONTEXT.md: the public declarations of the shared modules, one file per section.

It lets an agent learn the shared API without reading every source file. It is generated,
so it cannot drift: run it before each commit that touches core or engine.

Usage: python3 tools/context.py
"""

import pathlib
import re

ANDROID = pathlib.Path(__file__).resolve().parent.parent
MODULES = ["core", "engine/detection"]

DECLARATION = re.compile(
    r"^\s*(?:@\w+(?:\([^)]*\))?\s+)*"
    r"(?:(?:public|private|internal|protected|abstract|open|sealed|data|enum|inline|value|const|override"
    r"|operator|infix|suspend|lateinit|fun|annotation|companion)\s+)*"
    r"(fun|val|var|class|object|interface|typealias)\b"
)
HIDDEN = re.compile(r"^\s*(?:@\w+\s+)*(?:\w+\s+)*?(private|internal|protected)\b")
STRING = re.compile(r'"(?:[^"\\]|\\.)*"')
COMMENT = re.compile(r"/\*.*?\*/|//.*$")


def code(line):
    """The line without comments and string contents, for counting brackets."""
    return COMMENT.sub("", STRING.sub('""', line))


def cut_top_level(text, stops):
    """Text up to the first of [stops] that sits outside all brackets."""
    depth = 0
    for i, ch in enumerate(text):
        if ch in "(<[":
            depth += 1
        elif ch in ")]" or (ch == ">" and text[i - 1] != "-"):
            depth -= 1
        elif depth == 0:
            for stop in stops:
                if text.startswith(stop, i):
                    return text[:i].rstrip()
    return text.rstrip().removesuffix(" =")


def declarations(path):
    lines = path.read_text().splitlines()
    out = []
    stack = []  # One entry per open brace: "type" for a visible class body, else "other".
    annotation = None
    i = 0
    while i < len(lines):
        line = lines[i]
        stripped = line.strip()
        if stripped.startswith("@") and not DECLARATION.match(line) and stack.count("other") == 0:
            annotation = stripped.split("(")[0]
            i += 1
            continue
        m = DECLARATION.match(line) if all(k == "type" for k in stack) else None
        if not m:
            annotation = None
            for ch in code(line):
                if ch == "{":
                    stack.append("other")
                elif ch == "}" and stack:
                    stack.pop()
            i += 1
            continue
        # Join the declaration across lines until its parentheses close.
        text = COMMENT.sub("", line).strip()
        while code(text).count("(") > code(text).count(")") and i + 1 < len(lines):
            i += 1
            text += " " + COMMENT.sub("", lines[i]).strip()
        text = re.sub(r"\s+", " ", text).replace("( ", "(").replace(" )", ")").replace(" ,", ",")
        kind = m.group(1)
        hidden = bool(HIDDEN.match(text))
        if kind == "fun":
            shown = cut_top_level(text, [" {", " = "])
        elif kind in ("val", "var"):
            shown = cut_top_level(text, [" = ", " by ", " {"])
        else:
            shown = cut_top_level(text, [" {"])
        if not hidden:
            prefix = "    " * len(stack)
            out.append(prefix + (annotation + " " if annotation == "@Composable" else "") + shown)
        annotation = None
        # Open braces on the declaration's last line start its body.
        opens = code(text).count("{") - code(text).count("}")
        body = "type" if kind in ("class", "object", "interface") and not hidden else "other"
        for n in range(opens):
            stack.append(body if n == 0 else "other")
        for _ in range(-opens):
            if stack:
                stack.pop()
        i += 1
    return out


def main():
    parts = [
        "# Shared Android API",
        "",
        "Generated by `tools/context.py`. Do not edit. Public declarations of "
        + ", ".join(f"`{m}`" for m in MODULES)
        + ", without bodies. Read a source file only when a signature is not enough.",
    ]
    for module in MODULES:
        src = ANDROID / module / "src/main/kotlin"
        for path in sorted(src.rglob("*.kt")):
            decls = declarations(path)
            if not decls:
                continue
            parts += ["", f"## {path.relative_to(ANDROID)}", "", "```kotlin", *decls, "```"]
    (ANDROID / "CONTEXT.md").write_text("\n".join(parts) + "\n")


if __name__ == "__main__":
    main()
